/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package validationroutine;

/**
 *
 * @author 1-WFokinther
 */
public class postcodeGUI extends javax.swing.JFrame {

    /**
     * Creates new form postcodeGUI
     */
    public postcodeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPostcodeTitle = new javax.swing.JLabel();
        btnValidatePostcode = new javax.swing.JButton();
        txtfldEnterPostcode = new javax.swing.JTextField();
        lblIdentify = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPostcodeTitle.setText("Validate Postcode");
        getContentPane().add(lblPostcodeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 100, 30));

        btnValidatePostcode.setText("Validate");
        btnValidatePostcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidatePostcodeActionPerformed(evt);
            }
        });
        getContentPane().add(btnValidatePostcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        txtfldEnterPostcode.setText("Enter Postcode");
        getContentPane().add(txtfldEnterPostcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, 30));

        lblIdentify.setText("Postcode:");
        getContentPane().add(lblIdentify, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnValidatePostcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidatePostcodeActionPerformed
        new postcodeGUI().setVisible(true);
    }//GEN-LAST:event_btnValidatePostcodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(postcodeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(postcodeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(postcodeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(postcodeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new postcodeGUI().setVisible(true); replace postcodeGUI with next frame 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValidatePostcode;
    private javax.swing.JLabel lblIdentify;
    private javax.swing.JLabel lblPostcodeTitle;
    private javax.swing.JTextField txtfldEnterPostcode;
    // End of variables declaration//GEN-END:variables
}
